export const shortcuts = {
  'Cmd+K': 'Open command palette',
  'G then P': 'Go to Pull Requests',
  'G then D': 'Go to Dashboard',
  'G then S': 'Go to Security',
  'G then P': 'Go to Performance',
  'A': 'Analyze latest PR',
  'B': 'Toggle bloom effect',
  'Escape': 'Close modal/drawer',
  'Enter': 'Confirm action',
  'Tab': 'Navigate between elements',
  'Shift+Tab': 'Navigate backwards',
  'Arrow keys': 'Navigate lists',
  'Space': 'Toggle selection',
  'Delete': 'Remove item',
  'Ctrl+S': 'Save changes',
  'Ctrl+Z': 'Undo',
  'Ctrl+Y': 'Redo',
  'F1': 'Show help',
  'F5': 'Refresh data',
  'F11': 'Toggle fullscreen'
};

export const shortcutMap = {
  'Meta+k': 'openCommandPalette',
  'g p': 'goToPullRequests',
  'g d': 'goToDashboard',
  'g s': 'goToSecurity',
  'g p': 'goToPerformance',
  'a': 'analyzeLatestPR',
  'b': 'toggleBloom',
  'Escape': 'closeModal',
  'Enter': 'confirmAction',
  'Tab': 'nextElement',
  'Shift+Tab': 'previousElement',
  'ArrowUp': 'navigateUp',
  'ArrowDown': 'navigateDown',
  'ArrowLeft': 'navigateLeft',
  'ArrowRight': 'navigateRight',
  ' ': 'toggleSelection',
  'Delete': 'removeItem',
  'Meta+s': 'saveChanges',
  'Meta+z': 'undo',
  'Meta+Shift+z': 'redo',
  'F1': 'showHelp',
  'F5': 'refreshData',
  'F11': 'toggleFullscreen'
};
